# Examples of filtering
    # ALPINE - cron periodic spam.
        #if ($syslogfacility-text == "cron" and $programname == "crond" and $syslogseverity == 6 and $msg contains "cmd run-parts /etc/periodic/") then stop
    # FEDORA - stop the absolute spam fest that is auth.audit.
        #if $syslogfacility-text == "auth" and $programname == "audit" and $syslogseverity >= 5 then stop


# Template to enforce ms-accurate timestamps. If this is not present, rsyslog will send second-accurate timestamps.
template(name="MS_TIMESTAMP" type="string" string="<%pri%>1 %timegenerated:::date-rfc3339% %HOSTNAME% %app-name% %procid% - - %msg%\n")

# Send all auth,authpriv, and everything at notice(5) or higher severity. This setup is sending UDP syslogs to port 5140.
auth,authpriv.*;*.notice action(
    type="omfwd"
    target="<vl-server>"
    port="5140"
    protocol="udp"
    template="MS_TIMESTAMP"
    queue.type="LinkedList"
    queue.size="10000"
    action.resumeRetryCount="-1"
)
